### ISSUE TITLE
R CMD check warning about S3 method

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#1]
Running R CMD check generates the following warning:

```r
checking S3 generic/method consistency ... WARNING
  plot2:
    function(x, y, ...)
  plot2.formula:
    function(formula, data, type, xlim, ylim, main, sub, xlab, ylab, ann,
             axes, frame.plot, asp, grid, palette, palette.args,
             legend.position, legend.args, pch, ...)
  
  See section ‘Generic functions and methods’ in the ‘Writing R
  Extensions’ manual.
```

The current [dispatch calling](https://github.com/grantmcdermott/plot2/blob/dc051a08145744b9f1a9e17a1d91c36b08a6d2a3/R/plot2.R#L148) looks right to me. Maybe it's a roxygen2 issue? Or do I have to explicitly allow all arguments in each method?

**Comment by grantmcdermott** [comment]
Batcall to S3 maestro @zeileis in case you can spot anything obvious that I'm missing ;-)

**Comment by zeileis** [comment]
Disclaimer: I haven't actually tried the code, though, and I haven't looked at the documentation again.

Nevertheless: A couple of comments.

* The convention for S3 generic/method consistency is that the method should have all the arguments that the generic has (including ...). It may have additional arguments, though.
* However, the dispatch works correctly regardless of argument naming.
* An exception to the S3 generic/method consistency rule was that the first argument of *.formula methods should be called formula. However, I think that the opinion has changed on this exception and that it shouldn't be made anymore.

So I would expect that the checks want you to name the first two arguments of plot2.formula "x" and "y". In addition, you may have "formula" and "data" arguments but they shouldn't be the first two.

**Comment by zeileis** [comment]
What triggered the discussion about the inconsistency of naming the first argument of *.formula methods "formula" was this: <https://bugs.R-project.org/show_bug.cgi?id=18299>

The inconsistency lead to problems with piping in combination with the formula method of `aggregate()`. Hence, the first argument of `aggregate.formula()` was renamed from `formula` to `x`.

I had argued that the renaming of the first argument is good but that I would still support the `formula` argument for backward compatibility. Unfortunately, my proposed patch was not incorporated. In fact, no one from R Core even commented.

**Comment by zeileis** [comment]
Without having looked at the details of the code, I think the following might work:

* _Generic:_ `plot2(x, ...)`.  
  So the generic just has arguments `x` and `...` that all methods must implement.
* _Default:_ `plot2(x, y = NULL, by = NULL, data = NULL, [...], ...)`.  
  The default method then has the `y` argument and the other arguments.
* _Formula:_ `plot2(x, data, type, [...], formula, ...)`.
  The formula method has the first argument `x` for consistency but also provides the argument `formula` for convenience. Internally, you just need to catch that `x` and `formula` cannot both be specified simultaneously.

**Comment by grantmcdermott** [comment]
Just tested locally and it works. Thanks Achim!
