### ISSUE TITLE
v0.0.4 release

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#105]
@vincentarelbundock @zeileis Just a heads-up that I plan to "release" v0.0.4 tomorrow morning (Friday).

Obviously this is mostly _pro forma_, since we haven't submitted to CRAN yet and the R-universe builds are tagged to the latest commit. But I'd like to announce the new facet features, so people can test them.

After this release, I'd like to focus on the main things still needed before a CRAN release. Mainly that's deciding on the package name, fixing continuous legend support, and possibly adding histogram support. Hopefully we can tie up some other loose ends in the process.

**Comment by zeileis** [comment]
That sounds great! Two comments:

* In March my research semester starts. I hope that I will be able to put aside some more time for working on the package and helping with the release. Maybe even add factor support for `y` and `x` but I won't promise too much ;-)
* Regarding the package name: I don't have much to add apart from the points I had raised in the original discussion. In any case, none of my preferences were particularly strong and I think that this is really your call. If you like `plot2` best, then go with `plot2`.

**Comment by grantmcdermott** [comment]
Super. Please don't stress about contributions. I know that both of you are (very) busy and I'm happy for whatever inputs you can provide. Just wanted to give you a HU regarding releases.

Speaking of which, I just announced the release on Mastodon and BlueSky. I'm still on an extended Twitter break (ineffectual protest vote?) but please feel free to share on Twitter too if you are still active there.

**Comment by zeileis** [comment]
Thanks, will share on Mastodon on Monday morning (our time). I'm trying to stop using Twitter and haven't really started BlueSky.
