### ISSUE TITLE
R CMD check warning due to vignette build error

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#106]
@etiennebacher @vincentarelbundock Sorry to tag you guys again, but I'm running into an R CMD check error related, I believe, to `altdoc`.

``` r
❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘intro_tutorial.Rmd’
  Package has no Sweave vignette sources and no VignetteBuilder field.
```

Background is that I changed the name of the intro tutorial (from `get_started.Rmd` to `intro_tutorial.Rmd`) in https://github.com/grantmcdermott/plot2/commit/64ab583a2a5c6dc0d64a117e7581504ffa91c0fe.

But I updated `altdoc/docsify` at the same time to point to the new file and everything works fine when I run `altdoc::render_docs()` and `altdoc::preview_docs()` locally.

Any ideas what I'm doing wrong or missing?

**Comment by etiennebacher** [comment]
What if you add `VignetteBuilder: knitr` in `DESCRIPTION`?

In any case I think that's probably unrelated to `altdoc` since `docs` and `altdoc` should be in `Rbuildignore`

**Comment by grantmcdermott** [comment]
Thanks Etienne, adding that in DESCRIPTION by itself didn't quite do it. But adding the normal Rmd YAML to the vignette itself did the trick.

TBH though: Now I'm puzzled by how this was working before. Is there some special `altdoc` treatment for vignettes specifically named `get_started.Rmd`?

(I think Vincent might be in a better position to answer, since he did the original `plot2` website implementation.)

**Comment by etiennebacher** [comment]
No, we don't have a special handling for some vignette names. I also don't know why R CMD check didn't fail before without the YAML

**Comment by vincentarelbundock** [comment]
i'm a bit lost now. not sure what the problem was or is.
