### ISSUE TITLE
Website README has not updated

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#107]
(i.e., It doesn't match the README here on GitHub.)

Don't know why...

**Comment by vincentarelbundock** [comment]
Did you edit .md instead of .qmd?

**Comment by grantmcdermott** [comment]
Hmmm. No, I edited the .qmd and then rendered it as .md. Both in https://github.com/grantmcdermott/plot2/commit/5d9c0e2e76c49fd6da215b5e731e8d498f6faaaa.

Does it maybe need to be .rmd for the `altdoc` docsify GH Actions workflow?

**Comment by vincentarelbundock** [comment]
I don't think so. Did you want to switch to Quarto for the gallery I linked to yesterday? If so, I could look into all this at the same time.

**Comment by grantmcdermott** [comment]
That would be awesome, thanks!

**Comment by vincentarelbundock** [comment]
With Quarto websites, one problem is that there can't be a preamble in README.qmd. I have not found a workaround to this yet.

If you want to render the README.qmd to README.md, you have to do it manually with `quarto render README.qmd --to md`

**Comment by grantmcdermott** [comment]
> If you want to render the README.qmd to README.md, you have to do it manually with quarto render README.qmd --to md

Thanks helpful to know as a workaround in the interim. Just used this to fix a typo in the README and seems to work fine for our purposes ATM.

**Comment by grantmcdermott** [comment]
> With Quarto websites, one problem is that there can't be a preamble in README.qmd. I have not found a workaround to this yet.
>
> If you want to render the README.qmd to README.md, you have to do it manually with quarto render README.qmd --to md

Note to self: you need to manually remove the “.png” suffix that is added to the R-universe badge link in the README.md file.
