### ISSUE TITLE
Wishlist: Proper formula processing

### ISSUE THREAD

**Issue by zeileis** [grantmcdermott/plot2#3]
Currently, the `plot2.formula()` method does not actually do a full formula processing (building terms and model.frame etc.) but just extracts the variables from the `data` argument. However, this means that transformations cannot be used in the formula, e.g., `plot2(log(y) ~ x, ...)`.

Also, I wouldn't recommend doing the `|` handling in the formula by using string operations (grep etc.). This leads to problems with things like `plot(y ~ x | factor(z > 2 | z < -2), ...)`. I have been there, done that, and eventually implemented the `Formula` package which avoids all string-based operations.

**Comment by grantmcdermott** [comment]
Agree, we could run into problems. Do you think the second case is likely for a twoway plot, though (as opposed to a regression package)? Part of my motivation for keeping things as dumbed-down as possible is to keep this truly dependency free for platforms like WASM (though obvs Formula is very light).

**Comment by zeileis** [comment]
I definitely wouldn't do string-based formula processing, been bitten too often by that. But I understand the dependency issue. As we just have to decide between `y ~ x` and `y ~ x | z`, I think it should be possible to implement a lightweight version in base R directly using only formula (and no string) tools. Will have a look! (But not today...)
