### ISSUE TITLE
Unable to add further elements on the plot2() plot.

### ISSUE THREAD

**Issue by karoliskoncevicius** [grantmcdermott/plot2#6]
Seems like currently images produced by `plot2()` with a legend hijack `plot.window()` coordinates.
As a result adding additional points using the coordinate system of the original data no longer works:

    library(plot2)

    plot2(Sepal.Width ~ Sepal.Length | Species, iris)

    points(6,3)  # point not visible

Instead we have to specify elements in the range of 0-1:

    points(0.5,0.5)  # adds a point to the middle of the plot

I think this is because when you set a legend you start a new window on top of the existing one.
Maybe the par() settings are not correctly returned afterwards?

**Comment by grantmcdermott** [comment]
Yeah, ideally we should be able to do this. I'm not sure about the solution rn, but it may be necessary to add a corrective factor to the coordinate system before exit? 

Note that we reset `par` [here](https://github.com/grantmcdermott/plot2/blob/main/R/plot2.R#L384) on exit so that new plots after a `plot2` call appear without any additional legend space. One option we could try is making `reset_par` a visible function-level (or even global) argument for users to set manually.

**Comment by karoliskoncevicius** [comment]
Maybe it would be possible to add the legend without adjusting the plotting window?

https://stackoverflow.com/a/49501243/1953718

**Comment by grantmcdermott** [comment]
Thanks, agree that’s an elegant solution. I think I tried it with my original script, but could get legend placement at the bottom working nicely (which is where I’d like the default to be). I might be missing something though, so happy to be corrected.

Btw, just quick note of thanks for your deconstructed base plot tutorial and basetheme package. Both are excellent and linked in the README.

**Comment by grantmcdermott** [comment]
Hi @karoliskoncevicius,

This should be fixed if you grab the latest dev version.

``` r
library(plot2)

plot2(Sepal.Width ~ Sepal.Length | Species, iris)

points(6,3, pch = 17, col = "red")
```

![](https://i.imgur.com/XBVR1s9.png)

<sup>Created on 2023-04-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

PSA that the default legend arrangement will probably be changing soon, though (#7).

**Comment by karoliskoncevicius** [comment]
Hello again, @grantmcdermott . I see your changes and I tried this approach myself when I forked your repo. The issue here is that the y-axis is wrong. You can see on your own posted image that the point is not at "3".

**Comment by grantmcdermott** [comment]
Ah, I see. I still need to add the offset. Have to hunt easter eggs with the kids now, but will try later!

**Comment by grantmcdermott** [comment]
@karoliskoncevicius Hopefully #13 has done the trick now (see examples at the top of the PR thread). Please don't hesitate to raise other issues if you run into this again or other problems.
