### ISSUE TITLE
custom `mfrow` settings are not respected for grouped plots

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#65]
Fine without a legend:

``` r
library(plot2)

par(mfrow = c(1,2))
plot2(mpg ~ wt, mtcars)
plot2(wt ~ mpg, mtcars)
```

![](https://i.imgur.com/SP2hS55.png)

Not fine with a legend:

``` r

par(mfrow = c(1,2))
plot2(mpg ~ wt | cyl, mtcars)
```

![](https://i.imgur.com/SGfJGCq.png)

``` r
plot2(wt ~ mpg | cyl, mtcars)
```

![](https://i.imgur.com/SbvqC5I.png)

<sup>Created on 2023-08-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by grantmcdermott** [comment]
Stepping through the debugger, the problem appears to stem from the various `par(omd = ...)` calls in setting up the legend, (e.g. [here](https://github.com/grantmcdermott/plot2/blob/0c7db77cf96e01cb969f8aea6c8768f91e16284a/R/plot2.R#L487)) which are somehow (?) changing `par("mfg")` at the same time. (Maybe `par("new")` too?)

I don't really understand why it's doing this and fixing may require more duct tape than is worth... especially if we're going to be passing custom `par(mfrow = ..., mfg = ...)` settings internally for facets.

**Comment by zeileis** [comment]
Is it really the `par(...)`? I thought it was the `plot.new()` that causes the step to the next panel in mfrow.

**Comment by grantmcdermott** [comment]
Yeah I'm really puzzled by this behaviour. 

I might simply be conflating separate issues, but please free to test on your side. (E.g. Set a browser breakpoint [here](https://github.com/grantmcdermott/plot2/blob/0c7db77cf96e01cb969f8aea6c8768f91e16284a/R/plot2.R#L526) and run my second example above. If I do so and call `par("mfg")` immediately before and immediately after `par(omd = c(0, 1-w, 0, 1))` I get different results.)

**Comment by zeileis** [comment]
Interesting, I wasn't aware of that either. If one of the outer `par()` settings is touched, it seems to reset the plot somehow. Other parameters can be altered. For example, this is ok:

```
par(mfrow = c(1, 2))
plot(1:5)
par(mar = c(8, 6, 1, 1))
plot(5:1)
```

But this re-initializes the cycling through the panels:

```
par(mfrow = c(1, 2))
plot(1:5)
par(omd = c(0, 1, 0, 1))
plot(5:1)
```

Maybe the idea is that while cycling through the panels, we may only alter those parameters that are relevant _within_ the panel but not _across_ the panels?
