### ISSUE TITLE
Should default legend position be "right!" instead of "bottom!"?

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#7]
Would make it consistent with **ggplot2** and also seems more logical given the landscape orientation / aspect ratio of most plots. I'm leaning that way, but happy for others to way in with thoughts.

**Comment by zeileis** [comment]
I agree, my preference for the default position is also "right".

**Comment by zeileis** [comment]
Another question: Personally, I loathe the boxes around the base legends. In my opinion, `bty = "n"` would be the better default. What do you think?

**Comment by grantmcdermott** [comment]
Yeah, happy to go with bty = "n" too. 

(Ironically, that was my original default. But I charged it to bordered because I thought it was closer to the default plot() + legend() behaviour. Was likely overthinking it...)

I'll change both once @vincentarelbundock has had a chance to weigh in.

**Comment by nathaneastwood** [comment]
Right seems more natural to me

**Comment by vincentarelbundock** [comment]
I don’t have a view on this.
